name: Dependabot auto-merge
on: pull_request_target

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: {% raw %}"${{ secrets.GITHUB_TOKEN }}"{% endraw %}
      - name: Enable auto-merge for Dependabot PRs
        if:
          contains(steps.metadata.outputs.dependency-names, 'my-dependency') &&
          steps.metadata.outputs.update-type == 'version-update:semver-patch'
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: {% raw %}${{github.event.pull_request.html_url}}{% endraw %}
          GITHUB_TOKEN: {% raw %}${{secrets.GITHUB_TOKEN}}{% endraw %}
